apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-app-ingress
  labels:
    app: vote-app
spec:
  ingressClassName: nginx
  rules:
    - host: vote.prod.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vote-app-vote
                port:
                  number: 80

