replicaCount: 3

image:
  repository: omarghonim/devops-vote
  tag: "latest"

containerPort: 3000

service:
  port: 80

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

redis:
  host: "redis-master.prod.svc.cluster.local"

postgres:
  host: "postgres.prod.svc.cluster.local"
  password: ""

ingress:
  host: "vote.prod.local"

