replicaCount: 1

vote:
  image:
    repository: omarghonim/vote
    tag: latest
  containerPort: 8080

result:
  image:
    repository: omarghonim/result
    tag: latest
  containerPort: 4000


 
worker:
  image:
    repository: omarghonim/worker
    tag: latest


service:
  port: 80

  
resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

redis:
  host: "vote-app-redis-master"

postgres:
  host: "postgres"
  password: ""

ingress:
  enabled: true
  host: "vote.dev.local"
