apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vote
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.vote.containerPort }}
  selector:
    app: vote
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-result
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: result